05 calendar
js-tasks-ru/htmlcss-20230411_svetlana87 pull request #11
Opened 2023-05-05 16:31 UTC by Lana0001

2023-05-05 16:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-06 10:58 UTC, GSemikozov requested changes

2023-05-06 10:58 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 34px;
`28 26 32`

2023-05-07 20:33 UTC, Lana0001 commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 34px;
fix

2023-05-07 20:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 14:27 UTC, GSemikozov approved these changes

2023-05-11 14:28 UTC, merged