input v1
js-tasks-ru/htmlcss-20230411_svetlana87 pull request #20
Opened 2023-05-18 20:03 UTC by Lana0001

2023-05-18 20:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-18 21:14 UTC, GSemikozov requested changes

2023-05-18 21:14 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="input">
а вот в случае с инпутом все заворачивать в label не надо)

2023-05-18 21:14 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="input__title">Label</div>
вот это и есть label

2023-05-18 21:14 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input__icon">
чтобы показывать правильную иконку, проще задать модификаторы и уже по ним отображать

2023-05-18 21:14 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input__icon">
что и сделано ниже. Но все классы в разметке пусть будут сразу

2023-05-20 07:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-24 11:55 UTC, GSemikozov approved these changes

2023-05-24 11:55 UTC, merged