Карточки на главной странице
js-tasks-ru/htmlcss-20230411_svetlana87 pull request #9
Opened 2023-05-01 10:39 UTC by Lana0001

2023-05-01 10:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 14:50 UTC, GSemikozov requested changes

2023-05-01 14:50 UTC, GSemikozov commented on components/card/card.css
> +    padding: 32px;
`32 25`

2023-05-01 14:50 UTC, GSemikozov commented on components/main/main.css
> +    padding: 68px 165px;
вместо таких паддингов справа-слева лучше использовать общий container

2023-05-02 06:29 UTC, Lana0001 commented on components/main/main.css
> +    padding: 68px 165px;
т.е. перенести эти паддинги на class="main" ?

2023-05-02 06:29 UTC, Lana0001 commented on components/card/card.css
> +    padding: 32px;
ок, принято

2023-05-02 16:57 UTC, GSemikozov commented on components/main/main.css
> +    padding: 68px 165px;
нет, создать блок .container который выравниваем по середине и ограничиваем по ширине (точно так же как мы это делали на занятии)

2023-05-05 12:17 UTC, GSemikozov approved these changes

2023-05-05 12:17 UTC, merged